/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipes` | `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `/log/new`; params?: Router.UnknownInputParams; } | { pathname: `/recipes/new`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/recipes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recipes` | `/recipes`; params?: Router.UnknownOutputParams; } | { pathname: `/log/new`; params?: Router.UnknownOutputParams; } | { pathname: `/recipes/new`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/recipes/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/log${`?${string}` | `#${string}` | ''}` | `/log${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recipes${`?${string}` | `#${string}` | ''}` | `/recipes${`?${string}` | `#${string}` | ''}` | `/log/new${`?${string}` | `#${string}` | ''}` | `/recipes/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipes` | `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `/log/new`; params?: Router.UnknownInputParams; } | { pathname: `/recipes/new`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/recipes/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/recipes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
